[package]
name = "aoc-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
config = "0.13.4"
pico-args = "0.5.0"
reqwest = { version = "0.11.22", features = ["cookie_crate", "blocking"] }
serde =  { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
